# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigGenerator', '0003_auto_20170926_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.AddField(
            model_name='character',
            name='base_damage',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='base_defense',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='base_health',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='base_mana',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
